name: Scheduled scraper run

on:
  schedule:
    # 19:30 JST / 10:30 UTC every day
    - cron: '30 10 * * *'
  workflow_dispatch:

env:
  EDINET_CODE: ${{ vars.EDINET_CODE || 'E35239' }}
  DOWNLOAD_DIR: ${{ vars.DOWNLOAD_DIR || 'data/downloads' }}
  DB_PATH: ${{ vars.DB_PATH || 'data/database/edinet_reports.db' }}

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.7.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run scraper
        env:
          PYTHONUNBUFFERED: '1'
          EDINET_API_KEY: ${{ secrets.EDINET_API_KEY }}
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: poetry run python run_scraper.py
